# Generated by Django 5.2.8 on 2025-12-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe_plan',
            name='describe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
