# Generated by Django 5.2.8 on 2025-12-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscribe_plan'),
        ),
    ]
