# Generated by Django 5.2.8 on 2025-12-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_postsubscription_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsubscription',
            old_name='subscription',
            new_name='subscription_plan',
        ),
    ]
